### ISSUE TITLE
Standard/Convertible RI

### ISSUE THREAD

**Issue by Issif** [grahamc/ec2-reservation-pricing-comparison#1]
Hi, 

As AWS offers two types of RI now (standard and convertible), we have 2 items on each graph with same Name ('Partial Upfront (3 years)' for example.

Any chance to add "OfferingClass" in Legend?

Thanks.

Regards,

**Comment by grahamc** [comment]
Hmm... good question. I don't use AWS too much anymore, but I don't mind spending a bit of time trying to make this work. Now to figure out how the dang thing worked in the first place.... :)

**Comment by grahamc** [comment]
Fixed, thank you! I also added support for new regions :)

**Comment by Issif** [comment]
Awesome \o/

I tried and it works perfectly.

Thanks a lot.

**Comment by grahamc** [comment]
Great! You're welcome :) I'm glad it was an easy fix.
